server:
  port: 8080

stockmaster:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  jpa:
    show-sql: true
    open-in-view: false
  devtools:
    livereload:
      port: 35731
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/stockmaster
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: B6Yk6S3NsFvhdSBgvffdpdrDRmrKdOt5
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
logging:
  level:
    sql: info