server:
  port: 8082

stockmaster:
  services:
    catalogue:
      uri: http://localhost:8081
      username: catalogue_service_user
      password: password

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  flyway:
    schemas:
      - public
      - user_management
  jpa:
    show-sql: true
    open-in-view: false
  devtools:
    livereload:
      port: 35731

logging:
  level:
    sql: info