server:
  port: 8082


stockmaster:
  services:
    catalogue:
      uri: http://localhost:8081
      user:
        name: catalogue_service_user
        password: password

spring:
  devtools:
    livereload:
      port: 35731
  jpa:
    open-in-view: false