server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://172.20.10.4:5432/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/stockmaster
  devtools:
    livereload:
      port: 35730

logging:
  level:
    sql: info
